// @generated - This file is generated by atrium-codegen. DO NOT EDIT.
//!Definitions for the `com.atproto.sync.refreshIdentity` namespace.
pub const NSID: &str = "com.atproto.sync.refreshIdentity";
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub struct InputData {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub hostname: Option<crate::types::string::AtIdentifier>,
}
pub type Input = crate::types::Object<InputData>;
pub type Output = crate::com::atproto::identity::defs::AtprotoIdentity;
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Eq)]
#[serde(tag = "error", content = "message")]
pub enum Error {}
impl std::fmt::Display for Error {
    fn fmt(&self, _f: &mut std::fmt::Formatter) -> std::fmt::Result {
        Ok(())
    }
}
