// @generated - This file is generated by atrium-codegen. DO NOT EDIT.
//!Definitions for the `com.atproto.identity.defs` namespace.
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub struct AtprotoIdentityData {
    pub did: crate::types::string::Did,
    ///The complete DID document for the identity.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub did_doc: Option<crate::types::Unknown>,
    ///The validated handle of the account; or 'handle.invalid' if the handle did not resolve successfully.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub handle: Option<crate::types::string::Handle>,
    ///If true, the DID has been deleted, and the other optional fields (eg, handle and didDoc) should be null.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub tombstoned: Option<bool>,
}
pub type AtprotoIdentity = crate::types::Object<AtprotoIdentityData>;
